services:
  db:
    image: postgres:16
    container_name: sp-postgres
    environment:
      POSTGRES_DB: sp-db
      POSTGRES_USER: basinger
      POSTGRES_PASSWORD: "Fel96396597!"
      TZ: "Europe/Rome"
    ports:
      - "5433:5432"  # если занят, сделай "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U basinger -d sp-db"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

volumes:
  pgdata:

