# Generated by Django 5.2.4 on 2025-09-08 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва проєкту')),
                ('description', models.TextField(help_text='Основний опис/лід для картки', verbose_name='Опис')),
                ('goal', models.TextField(blank=True, help_text='Текст для блоку «Мета»', verbose_name='Мета')),
                ('partners', models.TextField(blank=True, help_text='Текст для блоку «Партнери»', verbose_name='Партнери')),
                ('results', models.TextField(blank=True, help_text='Текст для блоку «Результати»', verbose_name='Результати')),
                ('is_reverse', models.BooleanField(default=False, verbose_name='Реверсувати макет (текст зліва, фото справа)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Слаг')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Проєкт',
                'verbose_name_plural': 'Проєкти',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='Текст бейджа')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='main.project')),
            ],
            options={
                'verbose_name': 'Бейдж проєкту',
                'verbose_name_plural': 'Бейджі проєкту',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Зображення')),
                ('alt', models.CharField(blank=True, max_length=255, verbose_name='Alt (опис зображення)')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.project')),
            ],
            options={
                'verbose_name': 'Зображення проєкту',
                'verbose_name_plural': 'Зображення проєкту',
                'ordering': ['order', 'id'],
            },
        ),
    ]
