# Generated by Django 5.2.4 on 2025-09-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project_projectbadge_projectimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Підрозділ')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Підрозділ організації',
                'verbose_name_plural': 'Підрозділи організації',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='units',
            field=models.ManyToManyField(blank=True, related_name='projects', to='main.orgunit', verbose_name='Підрозділи'),
        ),
    ]
