# Generated by Django 5.2.4 on 2025-09-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_orgunit_project_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='units',
        ),
        migrations.AddField(
            model_name='project',
            name='body',
            field=models.TextField(blank=True, help_text='Можна вставляти HTML/форматований текст', verbose_name='Детальний опис'),
        ),
        migrations.AddField(
            model_name='project',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Обкладинка (герой)'),
        ),
        migrations.AddField(
            model_name='project',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/og/', verbose_name='OG Image'),
        ),
        migrations.AddField(
            model_name='project',
            name='seo_description',
            field=models.TextField(blank=True, verbose_name='SEO description'),
        ),
        migrations.AddField(
            model_name='project',
            name='seo_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO title'),
        ),
        migrations.AddField(
            model_name='project',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, verbose_name='Підзаголовок'),
        ),
        migrations.AddField(
            model_name='project',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='Відео (YouTube/Vimeo/MP4)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Короткий опис / лід'),
        ),
        migrations.AlterField(
            model_name='project',
            name='goal',
            field=models.TextField(blank=True, verbose_name='Мета'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_reverse',
            field=models.BooleanField(default=False, verbose_name='Реверсувати макет у списку'),
        ),
        migrations.AlterField(
            model_name='project',
            name='partners',
            field=models.TextField(blank=True, verbose_name='Партнери'),
        ),
        migrations.AlterField(
            model_name='project',
            name='results',
            field=models.TextField(blank=True, verbose_name='Результати'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Слаг'),
        ),
    ]
