# Generated by Django 5.2.4 on 2025-09-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_project_units_project_body_project_cover_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='body',
        ),
        migrations.RemoveField(
            model_name='project',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='project',
            name='og_image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='seo_title',
        ),
        migrations.RemoveField(
            model_name='project',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='project',
            name='video_url',
        ),
        migrations.AddField(
            model_name='project',
            name='units',
            field=models.ManyToManyField(blank=True, related_name='projects', to='main.orgunit', verbose_name='Підрозділи'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Основний опис/лід для картки', verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='project',
            name='goal',
            field=models.TextField(blank=True, help_text='Текст для блоку «Мета»', verbose_name='Мета'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_reverse',
            field=models.BooleanField(default=False, verbose_name='Реверсувати макет (текст зліва, фото справа)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='partners',
            field=models.TextField(blank=True, help_text='Текст для блоку «Партнери»', verbose_name='Партнери'),
        ),
        migrations.AlterField(
            model_name='project',
            name='results',
            field=models.TextField(blank=True, help_text='Текст для блоку «Результати»', verbose_name='Результати'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Слаг'),
        ),
    ]
