# Generated by Django 5.2.4 on 2025-09-08 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_project_body_remove_project_cover_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг детальної сторінки')),
                ('title_override', models.CharField(blank=True, max_length=255, verbose_name='Заголовок (детально)')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Підзаголовок')),
                ('lead', models.TextField(blank=True, verbose_name='Короткий лід/опис')),
                ('body', models.TextField(blank=True, verbose_name='Детальний опис (HTML дозволено)')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='projects/detail/', verbose_name='Обкладинка (герой)')),
                ('video_url', models.URLField(blank=True, verbose_name='Відео (YouTube/Vimeo/MP4)')),
                ('goal', models.TextField(blank=True, verbose_name='Мета (override)')),
                ('partners', models.TextField(blank=True, verbose_name='Партнери (override)')),
                ('results', models.TextField(blank=True, verbose_name='Результати (override)')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO title')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO description')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='projects/detail/og/', verbose_name='OG image')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Детальна сторінка проєкту',
                'verbose_name_plural': 'Детальні сторінки проєктів',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='detail',
            field=models.OneToOneField(blank=True, help_text='Опціонально: прив’яжіть детальну сторінку для «Дізнатися більше».', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='main.projectdetail', verbose_name='Детальна сторінка'),
        ),
        migrations.CreateModel(
            name='ProjectDetailImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/detail/gallery/')),
                ('alt', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.projectdetail', verbose_name='Проєкт (детально)')),
            ],
            options={
                'verbose_name': 'Зображення (детально)',
                'verbose_name_plural': 'Галерея (детально)',
                'ordering': ['order', 'id'],
            },
        ),
    ]
