# Generated by Django 5.2.4 on 2025-09-08 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_projectdetail_project_detail_projectdetailimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetailGridImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/grid/', verbose_name='Зображення')),
                ('alt', models.CharField(blank=True, max_length=255, verbose_name='ALT')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grid_images', to='main.projectdetail', verbose_name='Проєкт')),
            ],
            options={
                'verbose_name': 'Зображення полотна',
                'verbose_name_plural': 'Зображення полотна',
                'ordering': ('order', 'id'),
            },
        ),
    ]
