# Generated by Django 5.2.4 on 2025-10-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_projectdetailgridimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_reverse_education',
            field=models.BooleanField(default=False, verbose_name='Реверс для сторінки: Освіта'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_reverse_platform',
            field=models.BooleanField(default=False, verbose_name='Реверс для сторінки: Громадська платформа'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_reverse_sport',
            field=models.BooleanField(default=False, verbose_name='Реверс для сторінки: Спорт'),
        ),
    ]
