# Generated by Django 5.2.7 on 2025-10-11 20:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_project_is_reverse_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='video_file',
            field=models.FileField(blank=True, upload_to='projects/detail/video/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg'])], verbose_name='Відеофайл'),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='video_poster',
            field=models.ImageField(blank=True, null=True, upload_to='projects/detail/video/posters/', verbose_name='Обкладинка відео (poster)'),
        ),
    ]
