# Generated by Django 5.2.7 on 2025-11-04 19:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_projectdetail_video_file_projectdetail_video_poster'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Підзаголовок')),
                ('lead', models.TextField(blank=True, verbose_name='Короткий вступ/лід')),
                ('body', models.TextField(blank=True, verbose_name='Текст статті (HTML дозволено)')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='news/covers/', verbose_name='Головне фото')),
                ('video_url', models.URLField(blank=True, verbose_name='Відео (YouTube/Vimeo/MP4 URL)')),
                ('video_file', models.FileField(blank=True, upload_to='news/video/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg'])], verbose_name='Відеофайл')),
                ('video_poster', models.ImageField(blank=True, null=True, upload_to='news/video/posters/', verbose_name='Постер відео (poster)')),
                ('author_name', models.CharField(blank=True, max_length=160, verbose_name="Автор (ім'я для відображення)")),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубліковано')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публікації')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO title')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO description')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='news/og/', verbose_name='OG image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_articles', to=settings.AUTH_USER_MODEL, verbose_name="Автор (зв'язок з користувачем)")),
            ],
            options={
                'verbose_name': 'Новина',
                'verbose_name_plural': 'Новини',
                'ordering': ('-published_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/gallery/', verbose_name='Зображення')),
                ('alt', models.CharField(blank=True, max_length=255, verbose_name='ALT')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.newsarticle', verbose_name='Стаття')),
            ],
            options={
                'verbose_name': 'Зображення статті',
                'verbose_name_plural': 'Галерея статті',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['-published_at'], name='main_newsar_publish_6a1c69_idx'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['is_published', 'published_at'], name='main_newsar_is_publ_6ed3e0_idx'),
        ),
    ]
